### PR TITLE
Add beginning of a test suite.

### PR DESCRIPTION
**Pull request by jamadden**
This borrows some code from the sphinx test suite (which they do not
distribute.)

Add tox and travis support.

Remove support for Sphinx < 1.0.

Remove helper unicode function since we dont run on 2.6 on 3.2 anymore.

### CODE REVIEW

**Comment by jamadden** [comment]
Travis hooks will need to be enabled for this repo to see the results.

**Comment by tseaver** [comment]
@jamadden I just [added the Travis integration](https://travis-ci.org/repoze/repoze.sphinx.autointerface), but didn't want to duplicate your `.travis.yml` etc.  Can you re-push a trivial change (even just `$ git commit --amend && git push -f origin testing` would do) to exercise it?

**Comment by jamadden** [comment]
Thanks. Building now; I expect to need to tweak the travis config a few times.

**Comment by jamadden** [comment]
Welp, as a matter of fact, all four builds went green and ran all (both!) tests on the first try.

**Comment by jamadden** [comment]
FWIW, with those two tests the coverage looks like this:

```
Name                                                                                    Stmts   Miss  Cover
---------------------------------------------------------------------------------------------------
repoze/__init__.py                                                        1      0   100%
repoze/sphinx/__init__.py                                                1      0   100%
repoze/sphinx/autointerface.py                                          76     13    83%
repoze/sphinx/tests/__init__.py                                             0      0   100%
```

If I get some time I can add a .coveragerc and see what it takes to bring that number up in a different PR.

**Comment by tseaver** [comment]
@jamadden Thanks, looks good.

**Pull request merged**
